################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/BusIn.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/BusInOut.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/BusOut.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/CAN.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/CallChain.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Ethernet.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FileBase.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FileLike.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FilePath.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FileSystemLike.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/I2C.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/I2CSlave.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/InterruptIn.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/InterruptManager.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/LocalFileSystem.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/RawSerial.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/SPI.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/SPISlave.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Serial.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/SerialBase.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Stream.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Ticker.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Timeout.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Timer.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/TimerEvent.cpp \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/retarget.cpp 

C_SRCS += \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/assert.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/board.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/error.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/gpio.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/lp_ticker_api.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/mbed_interface.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/pinmap_common.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/rtc_time.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/semihost_api.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/ticker_api.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/us_ticker_api.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/wait_api.c 

OBJS += \
./mbed/common/BusIn.o \
./mbed/common/BusInOut.o \
./mbed/common/BusOut.o \
./mbed/common/CAN.o \
./mbed/common/CallChain.o \
./mbed/common/Ethernet.o \
./mbed/common/FileBase.o \
./mbed/common/FileLike.o \
./mbed/common/FilePath.o \
./mbed/common/FileSystemLike.o \
./mbed/common/I2C.o \
./mbed/common/I2CSlave.o \
./mbed/common/InterruptIn.o \
./mbed/common/InterruptManager.o \
./mbed/common/LocalFileSystem.o \
./mbed/common/RawSerial.o \
./mbed/common/SPI.o \
./mbed/common/SPISlave.o \
./mbed/common/Serial.o \
./mbed/common/SerialBase.o \
./mbed/common/Stream.o \
./mbed/common/Ticker.o \
./mbed/common/Timeout.o \
./mbed/common/Timer.o \
./mbed/common/TimerEvent.o \
./mbed/common/assert.o \
./mbed/common/board.o \
./mbed/common/error.o \
./mbed/common/gpio.o \
./mbed/common/lp_ticker_api.o \
./mbed/common/mbed_interface.o \
./mbed/common/pinmap_common.o \
./mbed/common/retarget.o \
./mbed/common/rtc_time.o \
./mbed/common/semihost_api.o \
./mbed/common/ticker_api.o \
./mbed/common/us_ticker_api.o \
./mbed/common/wait_api.o 

C_DEPS += \
./mbed/common/assert.d \
./mbed/common/board.d \
./mbed/common/error.d \
./mbed/common/gpio.d \
./mbed/common/lp_ticker_api.d \
./mbed/common/mbed_interface.d \
./mbed/common/pinmap_common.d \
./mbed/common/rtc_time.d \
./mbed/common/semihost_api.d \
./mbed/common/ticker_api.d \
./mbed/common/us_ticker_api.d \
./mbed/common/wait_api.d 

CPP_DEPS += \
./mbed/common/BusIn.d \
./mbed/common/BusInOut.d \
./mbed/common/BusOut.d \
./mbed/common/CAN.d \
./mbed/common/CallChain.d \
./mbed/common/Ethernet.d \
./mbed/common/FileBase.d \
./mbed/common/FileLike.d \
./mbed/common/FilePath.d \
./mbed/common/FileSystemLike.d \
./mbed/common/I2C.d \
./mbed/common/I2CSlave.d \
./mbed/common/InterruptIn.d \
./mbed/common/InterruptManager.d \
./mbed/common/LocalFileSystem.d \
./mbed/common/RawSerial.d \
./mbed/common/SPI.d \
./mbed/common/SPISlave.d \
./mbed/common/Serial.d \
./mbed/common/SerialBase.d \
./mbed/common/Stream.d \
./mbed/common/Ticker.d \
./mbed/common/Timeout.d \
./mbed/common/Timer.d \
./mbed/common/TimerEvent.d \
./mbed/common/retarget.d 


# Each subdirectory must supply rules for building sources it contributes
mbed/common/BusIn.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/BusIn.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/BusIn.d" -MT"mbed/common/BusIn.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/BusInOut.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/BusInOut.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/BusInOut.d" -MT"mbed/common/BusInOut.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/BusOut.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/BusOut.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/BusOut.d" -MT"mbed/common/BusOut.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/CAN.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/CAN.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/CAN.d" -MT"mbed/common/CAN.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/CallChain.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/CallChain.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/CallChain.d" -MT"mbed/common/CallChain.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/Ethernet.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Ethernet.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/Ethernet.d" -MT"mbed/common/Ethernet.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/FileBase.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FileBase.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/FileBase.d" -MT"mbed/common/FileBase.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/FileLike.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FileLike.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/FileLike.d" -MT"mbed/common/FileLike.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/FilePath.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FilePath.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/FilePath.d" -MT"mbed/common/FilePath.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/FileSystemLike.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/FileSystemLike.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/FileSystemLike.d" -MT"mbed/common/FileSystemLike.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/I2C.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/I2C.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/I2C.d" -MT"mbed/common/I2C.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/I2CSlave.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/I2CSlave.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/I2CSlave.d" -MT"mbed/common/I2CSlave.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/InterruptIn.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/InterruptIn.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/InterruptIn.d" -MT"mbed/common/InterruptIn.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/InterruptManager.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/InterruptManager.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/InterruptManager.d" -MT"mbed/common/InterruptManager.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/LocalFileSystem.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/LocalFileSystem.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/LocalFileSystem.d" -MT"mbed/common/LocalFileSystem.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/RawSerial.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/RawSerial.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/RawSerial.d" -MT"mbed/common/RawSerial.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/SPI.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/SPI.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/SPI.d" -MT"mbed/common/SPI.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/SPISlave.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/SPISlave.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/SPISlave.d" -MT"mbed/common/SPISlave.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/Serial.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Serial.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/Serial.d" -MT"mbed/common/Serial.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/SerialBase.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/SerialBase.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/SerialBase.d" -MT"mbed/common/SerialBase.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/Stream.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Stream.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/Stream.d" -MT"mbed/common/Stream.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/Ticker.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Ticker.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/Ticker.d" -MT"mbed/common/Ticker.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/Timeout.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Timeout.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/Timeout.d" -MT"mbed/common/Timeout.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/Timer.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/Timer.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/Timer.d" -MT"mbed/common/Timer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/TimerEvent.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/TimerEvent.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/TimerEvent.d" -MT"mbed/common/TimerEvent.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/assert.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/assert.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/assert.d" -MT"mbed/common/assert.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/board.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/board.d" -MT"mbed/common/board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/error.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/error.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/error.d" -MT"mbed/common/error.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/gpio.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/gpio.d" -MT"mbed/common/gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/lp_ticker_api.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/lp_ticker_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/lp_ticker_api.d" -MT"mbed/common/lp_ticker_api.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/mbed_interface.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/mbed_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/mbed_interface.d" -MT"mbed/common/mbed_interface.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/pinmap_common.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/pinmap_common.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/pinmap_common.d" -MT"mbed/common/pinmap_common.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/retarget.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/retarget.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C++ Compiler'
	arm-none-eabi-g++ -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -MMD -MP -MF"mbed/common/retarget.d" -MT"mbed/common/retarget.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/rtc_time.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/rtc_time.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/rtc_time.d" -MT"mbed/common/rtc_time.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/semihost_api.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/semihost_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/semihost_api.d" -MT"mbed/common/semihost_api.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/ticker_api.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/ticker_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/ticker_api.d" -MT"mbed/common/ticker_api.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/us_ticker_api.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/us_ticker_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/us_ticker_api.d" -MT"mbed/common/us_ticker_api.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/common/wait_api.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/common/wait_api.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/common/wait_api.d" -MT"mbed/common/wait_api.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


