# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainclient.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainClient(object):
    def setupUi(self, MainClient):
        MainClient.setObjectName("MainClient")
        MainClient.resize(800, 460)
        self.centralWidget = QtWidgets.QWidget(MainClient)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 134))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.txtStatus = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtStatus.setFont(font)
        self.txtStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.txtStatus.setObjectName("txtStatus")
        self.gridLayout.addWidget(self.txtStatus, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setMinimumSize(QtCore.QSize(261, 26))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 130, 801, 261))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtCurrDate = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCurrDate.setFont(font)
        self.txtCurrDate.setText("")
        self.txtCurrDate.setObjectName("txtCurrDate")
        self.gridLayout_2.addWidget(self.txtCurrDate, 1, 5, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 4, 1, 1)
        self.txtDateAvgHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDateAvgHum.setFont(font)
        self.txtDateAvgHum.setText("")
        self.txtDateAvgHum.setObjectName("txtDateAvgHum")
        self.gridLayout_2.addWidget(self.txtDateAvgHum, 4, 2, 1, 2)
        self.txtDateMaxHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDateMaxHum.setFont(font)
        self.txtDateMaxHum.setText("")
        self.txtDateMaxHum.setObjectName("txtDateMaxHum")
        self.gridLayout_2.addWidget(self.txtDateMaxHum, 2, 2, 1, 2)
        self.btnQuit = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnQuit.setFont(font)
        self.btnQuit.setObjectName("btnQuit")
        self.gridLayout_2.addWidget(self.btnQuit, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setMaximumSize(QtCore.QSize(115, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.txtDateMinHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDateMinHum.setFont(font)
        self.txtDateMinHum.setText("")
        self.txtDateMinHum.setObjectName("txtDateMinHum")
        self.gridLayout_2.addWidget(self.txtDateMinHum, 3, 2, 1, 2)
        self.txtCurrHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtCurrHum.setFont(font)
        self.txtCurrHum.setText("")
        self.txtCurrHum.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCurrHum.setObjectName("txtCurrHum")
        self.gridLayout_2.addWidget(self.txtCurrHum, 1, 1, 1, 1)
        self.txtDateAvgTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDateAvgTemp.setFont(font)
        self.txtDateAvgTemp.setText("")
        self.txtDateAvgTemp.setObjectName("txtDateAvgTemp")
        self.gridLayout_2.addWidget(self.txtDateAvgTemp, 4, 5, 1, 2)
        self.txtDateMaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDateMaxTemp.setFont(font)
        self.txtDateMaxTemp.setText("")
        self.txtDateMaxTemp.setObjectName("txtDateMaxTemp")
        self.gridLayout_2.addWidget(self.txtDateMaxTemp, 2, 5, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.txtDateMinTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDateMinTemp.setFont(font)
        self.txtDateMinTemp.setText("")
        self.txtDateMinTemp.setObjectName("txtDateMinTemp")
        self.gridLayout_2.addWidget(self.txtDateMinTemp, 3, 5, 1, 2)
        self.txtMaxTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtMaxTemp.setFont(font)
        self.txtMaxTemp.setText("")
        self.txtMaxTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMaxTemp.setObjectName("txtMaxTemp")
        self.gridLayout_2.addWidget(self.txtMaxTemp, 2, 4, 1, 1)
        self.txtAvgHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtAvgHum.setFont(font)
        self.txtAvgHum.setText("")
        self.txtAvgHum.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAvgHum.setObjectName("txtAvgHum")
        self.gridLayout_2.addWidget(self.txtAvgHum, 4, 1, 1, 1)
        self.txtMinHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtMinHum.setFont(font)
        self.txtMinHum.setText("")
        self.txtMinHum.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMinHum.setObjectName("txtMinHum")
        self.gridLayout_2.addWidget(self.txtMinHum, 3, 1, 1, 1)
        self.txtMinTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtMinTemp.setFont(font)
        self.txtMinTemp.setText("")
        self.txtMinTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMinTemp.setObjectName("txtMinTemp")
        self.gridLayout_2.addWidget(self.txtMinTemp, 3, 4, 1, 1)
        self.txtCurrTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtCurrTemp.setFont(font)
        self.txtCurrTemp.setText("")
        self.txtCurrTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCurrTemp.setObjectName("txtCurrTemp")
        self.gridLayout_2.addWidget(self.txtCurrTemp, 1, 4, 1, 1)
        self.txtPackets = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.txtPackets.setFont(font)
        self.txtPackets.setObjectName("txtPackets")
        self.gridLayout_2.addWidget(self.txtPackets, 5, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.txtMaxHum = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtMaxHum.setFont(font)
        self.txtMaxHum.setText("")
        self.txtMaxHum.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMaxHum.setObjectName("txtMaxHum")
        self.gridLayout_2.addWidget(self.txtMaxHum, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 5, 2, 1, 2)
        self.txtAvgTemp = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.txtAvgTemp.setFont(font)
        self.txtAvgTemp.setText("")
        self.txtAvgTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.txtAvgTemp.setObjectName("txtAvgTemp")
        self.gridLayout_2.addWidget(self.txtAvgTemp, 4, 4, 1, 1)
        MainClient.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainClient)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        MainClient.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainClient)
        self.mainToolBar.setObjectName("mainToolBar")
        MainClient.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainClient)
        self.statusBar.setObjectName("statusBar")
        MainClient.setStatusBar(self.statusBar)

        self.retranslateUi(MainClient)
        QtCore.QMetaObject.connectSlotsByName(MainClient)

    def retranslateUi(self, MainClient):
        _translate = QtCore.QCoreApplication.translate
        MainClient.setWindowTitle(_translate("MainClient", "MainClient"))
        self.label.setText(_translate("MainClient", "Client RPi"))
        self.txtStatus.setText(_translate("MainClient", "Connecting..."))
        self.label_10.setText(_translate("MainClient", "Temperature"))
        self.btnQuit.setText(_translate("MainClient", "Quit"))
        self.label_5.setText(_translate("MainClient", "Max:"))
        self.label_6.setText(_translate("MainClient", "Min:"))
        self.txtPackets.setText(_translate("MainClient", "0"))
        self.label_13.setText(_translate("MainClient", "Average:"))
        self.label_7.setText(_translate("MainClient", "Humidity"))
        self.label_26.setText(_translate("MainClient", "Packets Received:"))

