# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 460)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(100, -20, 571, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(430, 120, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(110, 120, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtTemp = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp.setGeometry(QtCore.QRect(460, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtTemp.setFont(font)
        self.txtTemp.setObjectName("txtTemp")
        self.txtHumidity = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity.setGeometry(QtCore.QRect(130, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtHumidity.setFont(font)
        self.txtHumidity.setObjectName("txtHumidity")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(470, 60, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtDate_Current = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Current.setGeometry(QtCore.QRect(580, 160, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Current.setFont(font)
        self.txtDate_Current.setObjectName("txtDate_Current")
        self.txtTemp_Max = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp_Max.setGeometry(QtCore.QRect(460, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtTemp_Max.setFont(font)
        self.txtTemp_Max.setObjectName("txtTemp_Max")
        self.txtHumidity_Max = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity_Max.setGeometry(QtCore.QRect(130, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtHumidity_Max.setFont(font)
        self.txtHumidity_Max.setObjectName("txtHumidity_Max")
        self.txtDate_Max_Temp = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Max_Temp.setGeometry(QtCore.QRect(580, 200, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Max_Temp.setFont(font)
        self.txtDate_Max_Temp.setObjectName("txtDate_Max_Temp")
        self.txtTemp_Min = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp_Min.setGeometry(QtCore.QRect(460, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtTemp_Min.setFont(font)
        self.txtTemp_Min.setObjectName("txtTemp_Min")
        self.txtHumidity_Min = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity_Min.setGeometry(QtCore.QRect(130, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtHumidity_Min.setFont(font)
        self.txtHumidity_Min.setObjectName("txtHumidity_Min")
        self.txtDate_Min_Temp = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Min_Temp.setGeometry(QtCore.QRect(580, 240, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Min_Temp.setFont(font)
        self.txtDate_Min_Temp.setObjectName("txtDate_Min_Temp")
        self.txtTemp_Avg = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp_Avg.setGeometry(QtCore.QRect(460, 280, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtTemp_Avg.setFont(font)
        self.txtTemp_Avg.setObjectName("txtTemp_Avg")
        self.txtHumidity_Avg = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity_Avg.setGeometry(QtCore.QRect(130, 280, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtHumidity_Avg.setFont(font)
        self.txtHumidity_Avg.setObjectName("txtHumidity_Avg")
        self.txtDate_Avg_Temp = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Avg_Temp.setGeometry(QtCore.QRect(580, 280, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Avg_Temp.setFont(font)
        self.txtDate_Avg_Temp.setObjectName("txtDate_Avg_Temp")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(10, 190, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txtStatus = QtWidgets.QLabel(self.centralWidget)
        self.txtStatus.setGeometry(QtCore.QRect(560, 60, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtStatus.setFont(font)
        self.txtStatus.setObjectName("txtStatus")
        self.sldrTemp = QtWidgets.QSlider(self.centralWidget)
        self.sldrTemp.setGeometry(QtCore.QRect(100, 60, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.sldrTemp.setFont(font)
        self.sldrTemp.setMaximum(1)
        self.sldrTemp.setPageStep(1)
        self.sldrTemp.setOrientation(QtCore.Qt.Horizontal)
        self.sldrTemp.setObjectName("sldrTemp")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(70, 60, 21, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(160, 60, 21, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.btnQuit = QtWidgets.QPushButton(self.centralWidget)
        self.btnQuit.setGeometry(QtCore.QRect(80, 330, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.btnQuit.setFont(font)
        self.btnQuit.setObjectName("btnQuit")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(210, 330, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.txtPackets = QtWidgets.QLabel(self.centralWidget)
        self.txtPackets.setGeometry(QtCore.QRect(360, 330, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtPackets.setFont(font)
        self.txtPackets.setObjectName("txtPackets")
        self.txtDate_Max_Hum = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Max_Hum.setGeometry(QtCore.QRect(230, 200, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Max_Hum.setFont(font)
        self.txtDate_Max_Hum.setObjectName("txtDate_Max_Hum")
        self.txtDate_Min_Hum = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Min_Hum.setGeometry(QtCore.QRect(230, 240, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Min_Hum.setFont(font)
        self.txtDate_Min_Hum.setObjectName("txtDate_Min_Hum")
        self.txtDate_Avg_Hum = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Avg_Hum.setGeometry(QtCore.QRect(230, 280, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDate_Avg_Hum.setFont(font)
        self.txtDate_Avg_Hum.setObjectName("txtDate_Avg_Hum")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sensor RPi"))
        self.label_2.setText(_translate("MainWindow", "Temperature:"))
        self.label_3.setText(_translate("MainWindow", "Humidity:"))
        self.txtTemp.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity.setText(_translate("MainWindow", "80 %"))
        self.label_4.setText(_translate("MainWindow", "Status:"))
        self.txtDate_Current.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtTemp_Max.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity_Max.setText(_translate("MainWindow", "80 %"))
        self.txtDate_Max_Temp.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtTemp_Min.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity_Min.setText(_translate("MainWindow", "80 %"))
        self.txtDate_Min_Temp.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtTemp_Avg.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity_Avg.setText(_translate("MainWindow", "80 %"))
        self.txtDate_Avg_Temp.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.label_5.setText(_translate("MainWindow", "Max:"))
        self.label_6.setText(_translate("MainWindow", "Min:"))
        self.label_7.setText(_translate("MainWindow", "Average:"))
        self.txtStatus.setText(_translate("MainWindow", "Disconnected"))
        self.label_8.setText(_translate("MainWindow", "C"))
        self.label_9.setText(_translate("MainWindow", "F"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))
        self.txtDate_Max_Hum.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtDate_Min_Hum.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtDate_Avg_Hum.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.label_10.setText(_translate("MainWindow", "Packets Sent:"))
        self.txtPackets.setText(_translate("MainWindow", "0"))

