################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.c \
D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.c 

OBJS += \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.o \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.o 

C_DEPS += \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.d \
./mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.d 


# Each subdirectory must supply rules for building sources it contributes
mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_acmp.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_adc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_aes.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_assert.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_burtc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dac.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dbg.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_dma.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_ebi.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_emu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_i2c.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_idac.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_int.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lcd.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_lesense.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_letimer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_leuart.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_mpu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_msc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_opamp.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_pcnt.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_prs.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_rtc.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_system.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_timer.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_usart.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_vcmp.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.o: D:/Documents/Coursework/ECEN5023/Simplicity_Workspace/Libraries/mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m3 -mthumb '-DEFM32LG990F256=1' '-DDEBUG=1' -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\api" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\cmsis\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600\TOOLCHAIN_GCC_ARM" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\TARGET_EFM32LG_STK3600" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\inc" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\targets\hal\TARGET_Silicon_Labs\TARGET_EFM32\emlib\src" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\Libraries\mbed\common" -I"D:\Documents\Coursework\ECEN5023\Simplicity_Workspace\emptyCxxProject\inc" -O0 -Wall -c -fmessage-length=0 -fno-rtti -fno-exceptions -fno-common -fomit-frame-pointer -mno-sched-prolog -fno-builtin -ffunction-sections -fdata-sections -std=c99 -MMD -MP -MF"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.d" -MT"mbed/targets/hal/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_wdog.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


