# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\CU_Boulder\Documents\Coursework\ECEN5053\PSoC_Workspace\Lab5_Multiplexer.cydsn\Lab5_Multiplexer.cyprj
# Date: Sun, 20 Mar 2016 21:15:20 GMT
#set_units -time ns
create_clock -name {CyILO} -period 1000000 -waveform {0 500000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 333.33333333333331 -waveform {0 166.666666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {Clock_1} -source [get_pins {ClockBlock/clk_sync}] -edges {1 241 481} [list [get_pins {ClockBlock/aclk_glb_0}]]
create_clock -name {Clock_1(fixed-function)} -period 10000 -waveform {0 5000} [get_pins {ClockBlock/aclk_glb_ff_0}]


# Component constraints for D:\CU_Boulder\Documents\Coursework\ECEN5053\PSoC_Workspace\Lab5_Multiplexer.cydsn\TopDesign\TopDesign.cysch
# Project: D:\CU_Boulder\Documents\Coursework\ECEN5053\PSoC_Workspace\Lab5_Multiplexer.cydsn\Lab5_Multiplexer.cyprj
# Date: Sun, 20 Mar 2016 21:15:15 GMT
