# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 460)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(100, -20, 571, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(370, 120, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(210, 120, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txtTemp = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp.setGeometry(QtCore.QRect(400, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtTemp.setFont(font)
        self.txtTemp.setObjectName("txtTemp")
        self.txtHumidity = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity.setGeometry(QtCore.QRect(230, 160, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtHumidity.setFont(font)
        self.txtHumidity.setObjectName("txtHumidity")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(470, 60, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txtDate_Current = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Current.setGeometry(QtCore.QRect(530, 160, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtDate_Current.setFont(font)
        self.txtDate_Current.setObjectName("txtDate_Current")
        self.txtTemp_Max = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp_Max.setGeometry(QtCore.QRect(400, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtTemp_Max.setFont(font)
        self.txtTemp_Max.setObjectName("txtTemp_Max")
        self.txtHumidity_Max = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity_Max.setGeometry(QtCore.QRect(230, 200, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtHumidity_Max.setFont(font)
        self.txtHumidity_Max.setObjectName("txtHumidity_Max")
        self.txtDate_Max = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Max.setGeometry(QtCore.QRect(530, 200, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtDate_Max.setFont(font)
        self.txtDate_Max.setObjectName("txtDate_Max")
        self.txtTemp_Min = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp_Min.setGeometry(QtCore.QRect(400, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtTemp_Min.setFont(font)
        self.txtTemp_Min.setObjectName("txtTemp_Min")
        self.txtHumidity_Min = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity_Min.setGeometry(QtCore.QRect(230, 240, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtHumidity_Min.setFont(font)
        self.txtHumidity_Min.setObjectName("txtHumidity_Min")
        self.txtDate_Min = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Min.setGeometry(QtCore.QRect(530, 240, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtDate_Min.setFont(font)
        self.txtDate_Min.setObjectName("txtDate_Min")
        self.txtTemp_Avg = QtWidgets.QLabel(self.centralWidget)
        self.txtTemp_Avg.setGeometry(QtCore.QRect(400, 280, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtTemp_Avg.setFont(font)
        self.txtTemp_Avg.setObjectName("txtTemp_Avg")
        self.txtHumidity_Avg = QtWidgets.QLabel(self.centralWidget)
        self.txtHumidity_Avg.setGeometry(QtCore.QRect(230, 280, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtHumidity_Avg.setFont(font)
        self.txtHumidity_Avg.setObjectName("txtHumidity_Avg")
        self.txtDate_Avg = QtWidgets.QLabel(self.centralWidget)
        self.txtDate_Avg.setGeometry(QtCore.QRect(530, 280, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtDate_Avg.setFont(font)
        self.txtDate_Avg.setObjectName("txtDate_Avg")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(80, 190, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(80, 230, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(80, 270, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.txtStatus = QtWidgets.QLabel(self.centralWidget)
        self.txtStatus.setGeometry(QtCore.QRect(560, 60, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.txtStatus.setFont(font)
        self.txtStatus.setObjectName("txtStatus")
        self.horizontalSlider = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 60, 71, 21))
        self.horizontalSlider.setMaximum(1)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Sensor RPi"))
        self.label_2.setText(_translate("MainWindow", "Temperature:"))
        self.label_3.setText(_translate("MainWindow", "Humidity:"))
        self.txtTemp.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity.setText(_translate("MainWindow", "80 %"))
        self.label_4.setText(_translate("MainWindow", "Status:"))
        self.txtDate_Current.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtTemp_Max.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity_Max.setText(_translate("MainWindow", "80 %"))
        self.txtDate_Max.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtTemp_Min.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity_Min.setText(_translate("MainWindow", "80 %"))
        self.txtDate_Min.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.txtTemp_Avg.setText(_translate("MainWindow", "100 F"))
        self.txtHumidity_Avg.setText(_translate("MainWindow", "80 %"))
        self.txtDate_Avg.setText(_translate("MainWindow", "12/21/17 12:25:25 PM"))
        self.label_5.setText(_translate("MainWindow", "Max:"))
        self.label_6.setText(_translate("MainWindow", "Min:"))
        self.label_7.setText(_translate("MainWindow", "Average:"))
        self.txtStatus.setText(_translate("MainWindow", "Disconnected"))

